flagception:
    features:
        analysis:
            default: true
        analysis_fireworks:
            default: false
        analysis_fireworks_corona:
            default: true
        analysis_komfortofen:
            default: false
        station_history:
            default: false
