flagception:
    features:
        analysis:
            default: true
        analysis_fireworks:
            default: true
        analysis_komfortofen:
            default: true
        station_history:
            default: true
