komfortofen_analysis_old:
    path: /komfortofen
    defaults:
        _controller: App\Controller\AnalysisController::komfortofenAction

analysis_komfortofen:
    path: /analysis/komfortofen
    defaults:
        _controller: App\Controller\AnalysisController::komfortofenAction


analysis_fireworks_corona:
    path: /analysis/corona-silvester
    defaults:
        _controller: App\Controller\AnalysisController::coronaFireworksAction
