app_directory:
  resource: './routing/'
  type:     directory

controllers:
  resource: ../src/Controller/
  type: attribute

when@dev:
  web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

  web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler
