app.swagger_ui:
  path: /api/doc
  methods: [GET]
  defaults:
    _controller: nelmio_api_doc.controller.swagger_ui

controllers:
  resource: ../src/Controller/
  type: attribute

presta_sitemap:
  resource: "@PrestaSitemapBundle/config/routing.yml"

fos_js_routing:
  resource: '@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml'

privacy:
  path: /privacy
  defaults:
    _controller: App\Controller\TemplateController::staticAction
    templateName: privacy

impress:
  path: /impress
  defaults:
    _controller: App\Controller\TemplateController::staticAction
    templateName: impress

limits:
  path: /grenzwerte
  defaults:
    _controller: App\Controller\TemplateController::staticAction
    templateName: limits

pollutant_pm10:
  path: /schadstoffe/feinstaub
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: Static/Pollutant/feinstaub.html.twig

pollutant_no2:
  path: /schadstoffe/stickstoffdioxid
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: Static/Pollutant/stickstoffdioxid.html.twig

pollutant_so2:
  path: /schadstoffe/schwefeldioxid
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: Static/Pollutant/schwefeldioxid.html.twig

pollutant_co:
  path: /schadstoffe/kohlenmonoxid
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: Static/Pollutant/kohlenmonoxid.html.twig

pollutant_o3:
  path: /schadstoffe/ozon
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: Static/Pollutant/ozon.html.twig

when@dev:
  web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

  web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler

  _errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error
