name: PHPStan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: iconv, json, simplexml, intl, pdo_pgsql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress
